### ISSUE TITLE
Put "premium" data offer on showcase page of core datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahub-v2/frontend#261]
## Acceptance criteria

* [x] There is a banner that is noticeable and gives clear information about the offer
* [x] I can click to signup or learn more and get more info
* [x] I can signup by filling the form

## Tasks

* [x] create a banner on showcase page of core datasets
* [x] create a modal with more information about the offer
* [x] add signup form into the modal
* [x] deploy

## Analysis

As the DataHub team, we want visitors of `/core` page to easily notice about "premium" data offer so that probability of getting paid users increases.

As we want the offer to be easily noticable we can put a banner below the navbar but above the page body.

```
We're introducing a premium service that includes notifications, guaranteed updates and integration with your workflow.

Sign up for our free trial program to find out more and tell us what you'd most want to see first!
```

* Notifications of data updates
* Notification of schema changes
* Warranty / guaranteed updates
* Workflow integration (e.g. python packages, node packages)
* Suggest your own feature ...
