### ISSUE TITLE
Collections 404 Page not rendering properly

### ISSUE THREAD

**Issue by tanvirchahal** [datahub-v2/frontend#415]
Collections 404 Page not rendering properly
How to reproduce: https://datahub.io/collections/xyz

## Acceptance Criteria
* [x] Nice 404 message is rendered instead of a messy error page
* [x] Changes are deployed

## Tasks
* [x] Fix the 404 message
* [x] Test the page for various urls
* [x] Deploy
