### ISSUE TITLE
Prepare Datahub Template Deck

### ISSUE THREAD

**Issue by tanvirchahal** [datahub-v2/frontend#422]
## User stories
* As Datopian we want a standard, elegant deck that conveys our brand, that we can use for all our work that is easy to use, so that we come across memorably and distinctively to clients and internally
* As Datopian, we want a standardized template deck, so that we can save time while preparing a presentation to clients / prospective clients 

## What slides do we want:
* Title slide
* Standard bullets (should we never have this?)
* Section heading
* Section summary
* Section indications (optional)
* Logo / report info at bottom e.g. DataHub Strategy
* Logo insertion

## Notes on approach
* Fonts, sizes
* Serif Pro for titles
* Source sans for text (but no examples of a lot of text)
* Colour / emphasis - like red in hdx

## Acceptance Criteria 
* [ ] Slide deck designs brainstormed
* [ ] Slide deck with various master pages is ready
* [ ] Fonts and verbiage is accurate
* [ ] Final review by Esteban or Rufus

## Tasks
* [ ] Get samples of deck
* [ ] Identify slides we need in master
* [ ] Create slides
* [ ] Focus on fonts, spacing and color combinations
